import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import Intersection from './Intersection';
import Interfaces from './Interfaces';
import TypeGuardsDiscrUnons from './TypeGuards&DiscrUnons';

import styles from '../styles/Home.module.css';

const Home = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Interfaces />
      <Intersection />
      <TypeGuardsDiscrUnons />
    </React.Fragment>
  );
};

export default Home;
